### ISSUE TITLE
Misspelling: gitlab

### ISSUE THREAD

**Issue by moh3n9595** [divar-ir/frontend-course#1]
I think **GitLab** is not related to [this](https://divar-ir.github.io/frontend-course/course/es6-and-tools.html#%DA%A9%D9%86%D8%AA%D8%B1%D9%84-%D9%86%D8%B3%D8%AE%D9%87-%D9%88-gitlab) part. Maybe your mean is something like **GitHub**? Right?

**Comment by mohtada-h** [comment]
that's right🙏
